#!/usr/bin/env node
// Headless report generator: node cli.js <url> [--out report.html] [--json]
// Runs the same scan engine as the web UI and reuses its exact styles/render
// code, so the standalone report looks identical to the live dashboard.
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { runScan } = require('./scanner.js');

function parseArgs(argv) {
  const args = { out: null, json: false, url: null };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--out' || a === '-o') args.out = argv[++i];
    else if (a === '--json') args.json = true;
    else if (!args.url && !a.startsWith('-')) args.url = a;
  }
  return args;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.url) {
    console.error('Usage: node cli.js <url> [--out report.html] [--json]');
    console.error('Example: node cli.js https://example.com');
    process.exit(1);
  }

  console.log(`Scanning ${args.url} ...`);
  console.log('Only scan sites you own or are explicitly authorized to test.\n');

  let result;
  try {
    result = await runScan(args.url, {
      onEvent: (e) => {
        if (e.type === 'progress') console.log(`  · ${e.label}`);
        if (e.type === 'finding') console.log(`    [${e.finding.severity.toUpperCase()}] ${e.finding.title}`);
      },
    });
  } catch (err) {
    console.error(`\nScan failed: ${err.message}`);
    process.exit(1);
  }

  console.log(`\nScore: ${result.score}/100 (Grade ${result.grade})`);
  console.log(`Findings: ${result.findings.length}`);

  if (args.json) {
    console.log(JSON.stringify(result, null, 2));
  }

  const outPath = path.resolve(args.out || `scan-report-${safeName(result.finalUrl)}.html`);
  const html = renderStaticReport(result);
  fs.writeFileSync(outPath, html, 'utf8');
  console.log(`\nHTML report written to ${outPath}`);
}

function safeName(url) {
  return url.replace(/^https?:\/\//, '').replace(/[^\w.-]/g, '_').slice(0, 60);
}

function renderStaticReport(result) {
  const publicDir = path.join(__dirname, 'public');
  const css = fs.readFileSync(path.join(publicDir, 'styles.css'), 'utf8');
  const appJs = fs.readFileSync(path.join(publicDir, 'app.js'), 'utf8');
  const dataJson = JSON.stringify(result).replace(/</g, '\\u003c');

  return `<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Scan report — ${escapeHtml(result.finalUrl)}</title>
<link href="https://fonts.googleapis.com/css2?family=Archivo:wght@600;700;800&family=Public+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@500;600&display=swap" rel="stylesheet">
<style>${css}</style>
</head>
<body>
<div class="page">
  <header class="topbar">
    <div class="brand">
      <span class="brand-mark">◈</span>
      <div>
        <h1>GMC Vulnerability Scanner — Report</h1>
        <p class="tagline">Passive security posture scan, generated ${escapeHtml(new Date(result.scannedAt).toLocaleString())}.</p>
      </div>
    </div>
  </header>
  <main>
    <section class="panel scan-panel hidden"></section>
    <section id="progress-panel" class="panel progress-panel hidden"></section>
    <section id="error-panel" class="panel error-panel hidden"><strong></strong><p id="error-message"></p></section>
    <section id="results" class="results hidden">
      <div class="panel summary-panel">
        <div class="grade-badge" id="grade-badge">A</div>
        <div class="summary-main">
          <div class="summary-target" id="summary-target">—</div>
          <div class="summary-meta" id="summary-meta">—</div>
          <div class="severity-chips" id="severity-chips"></div>
        </div>
        <div class="summary-actions">
          <button id="download-json" class="btn btn-ghost">Download JSON</button>
          <button id="print-report" class="btn btn-ghost">Print / Save PDF</button>
        </div>
      </div>
      <div id="notes-panel" class="panel notes-panel hidden">
        <strong>Some checks were skipped:</strong>
        <ul id="notes-list"></ul>
      </div>
      <div class="panel findings-panel">
        <div class="findings-header">
          <h2>Findings</h2>
          <div class="filter-row" id="filter-row"></div>
        </div>
        <div id="findings-list" class="findings-list"></div>
        <p id="no-findings" class="hidden">No issues found by these checks.</p>
      </div>
    </section>
  </main>
  <footer class="footer">
    <p class="fine-print">Generated by the GMC Vulnerability Scanner CLI. Passive, non-destructive checks only.</p>
  </footer>
</div>
<script>window.__SCAN_DATA__ = ${dataJson};</script>
<script>${appJs}</script>
</body>
</html>`;
}

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

main();
