// Static knowledge base: for every check the scanner can run, the plain-
// English explanation of the risk, how an attacker would realistically use
// it against a site (no working exploit code — just the well-known public
// attack pattern), and how to fix it. Findings produced by scanner.js
// reference these by id and attach the specific evidence they found.
'use strict';

const KB = {
  'no-https': {
    title: 'Site is served over plain HTTP',
    category: 'Transport Security',
    severity: 'critical',
    description: 'The site does not use HTTPS at all, or does not redirect HTTP traffic to HTTPS.',
    attack: 'Anyone on the same network as a visitor — public Wi-Fi, a compromised router, a malicious ISP — can read and modify every request and response in plain text (a classic man-in-the-middle attack). That includes login forms, session cookies, and any personal data the page collects.',
    fix: 'Obtain a TLS certificate (Let\'s Encrypt is free) and serve the entire site over HTTPS. Add a server-level redirect from http:// to https:// for every path so no page is ever reachable over plain HTTP.',
    references: ['OWASP: Transport Layer Protection Cheat Sheet'],
  },
  'tls-weak-protocol': {
    title: 'Outdated TLS protocol version negotiated',
    category: 'Transport Security',
    severity: 'high',
    description: 'The server negotiated an old TLS version (TLS 1.0 or 1.1, or SSLv3) that has known weaknesses.',
    attack: 'Older TLS versions are vulnerable to downgrade and padding-oracle style attacks (e.g. POODLE, BEAST). An attacker positioned on the network can sometimes force a connection to use the weak version, then work to recover parts of the encrypted traffic.',
    fix: 'Disable TLS 1.0/1.1 and SSLv3 in the web server or load balancer config, and only offer TLS 1.2 and 1.3.',
    references: ['Mozilla SSL Configuration Generator'],
  },
  'tls-cert-expired': {
    title: 'TLS certificate has expired',
    category: 'Transport Security',
    severity: 'critical',
    description: 'The server\'s TLS certificate is past its expiry date.',
    attack: 'Browsers will show visitors a hard security warning, training them to click through TLS errors — which also makes it easier for an attacker running a real man-in-the-middle attack (with their own certificate) to go unnoticed.',
    fix: 'Renew the certificate immediately and set up automatic renewal (certbot --renew-hook, or your host\'s auto-renew feature) so this cannot happen again.',
    references: [],
  },
  'tls-cert-expiring-soon': {
    title: 'TLS certificate expires soon',
    category: 'Transport Security',
    severity: 'low',
    description: 'The TLS certificate is valid but will expire within the next 14 days.',
    attack: 'No immediate exploit — but if it lapses unnoticed, visitors get browser warnings and any automated clients (apps, webhooks) may hard-fail.',
    fix: 'Renew now and confirm automatic renewal is actually configured and working.',
    references: [],
  },
  'tls-cert-untrusted': {
    title: 'TLS certificate is self-signed or not trusted',
    category: 'Transport Security',
    severity: 'high',
    description: 'The certificate chain does not validate against a trusted root (self-signed, expired root, or wrong chain order).',
    attack: 'Because the browser cannot verify the server\'s identity, visitors either see a warning or (if they\'ve been trained to ignore it) may not notice when a real attacker substitutes their own self-signed certificate in a man-in-the-middle attack.',
    fix: 'Install a certificate issued by a publicly trusted CA (Let\'s Encrypt, etc.) and make sure the full chain, not just the leaf certificate, is served.',
    references: [],
  },
  'tls-cert-hostname-mismatch': {
    title: 'TLS certificate does not match the hostname',
    category: 'Transport Security',
    severity: 'high',
    description: 'The certificate\'s subject/SAN list does not include the hostname the site is served on.',
    attack: 'Visitors get a browser warning that trains them to click through TLS errors, and it signals the certificate may be misconfigured or shared incorrectly across unrelated hosts.',
    fix: 'Issue a certificate that explicitly covers this hostname (and any aliases) in its Subject Alternative Name list.',
    references: [],
  },
  'hsts-missing': {
    title: 'No HTTP Strict-Transport-Security header',
    category: 'HTTP Headers',
    severity: 'medium',
    description: 'The site does not send a Strict-Transport-Security (HSTS) header.',
    attack: 'Without HSTS, a visitor\'s very first request to the site (or any request after their browser cache is cleared) can go out over plain HTTP before any redirect happens. An attacker in a position to intercept that first request (e.g. on public Wi-Fi, using a tool like sslstrip) can silently keep the victim on HTTP and intercept everything.',
    fix: 'Add `Strict-Transport-Security: max-age=31536000; includeSubDomains; preload` to every HTTPS response, and submit the domain to the HSTS preload list once you\'re confident every subdomain supports HTTPS.',
    references: ['OWASP: HTTP Strict Transport Security Cheat Sheet'],
  },
  'hsts-weak': {
    title: 'Strict-Transport-Security header has a weak configuration',
    category: 'HTTP Headers',
    severity: 'low',
    description: 'HSTS is present but max-age is short or includeSubDomains is missing.',
    attack: 'A short max-age means protection lapses quickly after a visitor\'s last visit, re-opening the downgrade-attack window described above. Missing includeSubDomains leaves subdomains unprotected even if the main domain is safe.',
    fix: 'Set max-age to at least 31536000 (one year) and add includeSubDomains once all subdomains genuinely support HTTPS.',
    references: [],
  },
  'csp-missing': {
    title: 'No Content-Security-Policy header',
    category: 'HTTP Headers',
    severity: 'medium',
    description: 'The site does not send a Content-Security-Policy (CSP) header.',
    attack: 'CSP is the main browser-side defense against cross-site scripting (XSS). Without it, if an attacker manages to inject a `<script>` tag anywhere (a comment field, a search box reflected into the page, a compromised third-party widget), the browser will happily execute it — letting the attacker steal session cookies, log keystrokes, or act as the logged-in user.',
    fix: 'Add a Content-Security-Policy header, starting restrictive (e.g. `default-src \'self\'`) and allow-listing only the specific script/style/image sources the site actually needs. Avoid `unsafe-inline` and `unsafe-eval` where possible.',
    references: ['OWASP: Content Security Policy Cheat Sheet'],
  },
  'csp-weak': {
    title: 'Content-Security-Policy allows unsafe sources',
    category: 'HTTP Headers',
    severity: 'medium',
    description: 'The CSP is present but allows `unsafe-inline`, `unsafe-eval`, or a wildcard (`*`) source.',
    attack: 'These directives largely defeat the purpose of CSP: `unsafe-inline` lets any injected inline `<script>` run, `unsafe-eval` lets injected code call `eval()`, and a wildcard script-src lets an attacker load a malicious script from any domain they control.',
    fix: 'Replace `unsafe-inline` with nonces or hashes for the specific inline scripts you need, drop `unsafe-eval` unless a dependency truly requires it, and replace wildcard sources with an explicit allow-list of domains.',
    references: [],
  },
  'clickjacking': {
    title: 'No clickjacking protection (X-Frame-Options / frame-ancestors)',
    category: 'HTTP Headers',
    severity: 'medium',
    description: 'Neither X-Frame-Options nor a CSP frame-ancestors directive restricts who can embed this page in an iframe.',
    attack: 'An attacker can embed the page in an invisible iframe on their own site, layer deceptive UI over it, and trick a logged-in visitor into clicking buttons on the real site (e.g. "confirm transfer", "change email") without realizing it — a classic clickjacking attack.',
    fix: 'Add `X-Frame-Options: DENY` (or SAMEORIGIN if framing by your own site is needed) and/or a CSP `frame-ancestors \'none\'` directive.',
    references: ['OWASP: Clickjacking Defense Cheat Sheet'],
  },
  'xcto-missing': {
    title: 'No X-Content-Type-Options header',
    category: 'HTTP Headers',
    severity: 'low',
    description: 'The site does not send `X-Content-Type-Options: nosniff`.',
    attack: 'Without this header, some browsers will "sniff" a response\'s content type instead of trusting the declared one. If an attacker can get the site to serve user-controlled content (e.g. an uploaded file) with an unexpected content type, sniffing can cause it to be interpreted as HTML/JS and executed, opening an XSS path.',
    fix: 'Add `X-Content-Type-Options: nosniff` to all responses.',
    references: [],
  },
  'referrer-policy-missing': {
    title: 'No Referrer-Policy header',
    category: 'HTTP Headers',
    severity: 'info',
    description: 'The site does not set a Referrer-Policy, so the browser default is used.',
    attack: 'Full URLs (which can contain session tokens, search terms, or internal paths in the query string) may leak to third-party sites via the Referer header when a visitor clicks an outbound link.',
    fix: 'Add `Referrer-Policy: strict-origin-when-cross-origin` (a safe modern default) or stricter.',
    references: [],
  },
  'permissions-policy-missing': {
    title: 'No Permissions-Policy header',
    category: 'HTTP Headers',
    severity: 'info',
    description: 'The site does not restrict which browser features (camera, microphone, geolocation, etc.) it or embedded third-party content may use.',
    attack: 'If a third-party script or iframe is ever compromised (e.g. via a supply-chain attack on an ad or analytics widget), an overly permissive policy lets it request access to the camera, microphone, or location without restriction.',
    fix: 'Add a `Permissions-Policy` header that disables features the site doesn\'t use, e.g. `Permissions-Policy: camera=(), microphone=(), geolocation=()`.',
    references: [],
  },
  'cors-wildcard-credentials': {
    title: 'CORS allows any origin together with credentials',
    category: 'CORS',
    severity: 'critical',
    description: 'The API responds with `Access-Control-Allow-Origin: *` (or reflects the request Origin) while also allowing credentials.',
    attack: 'This lets any website on the internet make authenticated requests to this API using the victim\'s existing session cookie and read the response — effectively letting an attacker\'s page act as the logged-in user and exfiltrate their data cross-site.',
    fix: 'Never combine `Access-Control-Allow-Credentials: true` with a wildcard or reflected origin. Maintain an explicit allow-list of trusted origins.',
    references: ['OWASP: CORS misconfiguration'],
  },
  'cors-wildcard': {
    title: 'CORS allows any origin',
    category: 'CORS',
    severity: 'low',
    description: 'The API responds with `Access-Control-Allow-Origin: *` for this request. No credentials are allowed, which limits the impact, but any site can still read non-credentialed responses.',
    attack: 'Any third-party website can call this endpoint from a visitor\'s browser and read the (non-authenticated) response, which can enable data scraping or abuse of rate-limited endpoints.',
    fix: 'If the API is not meant to be public, restrict Access-Control-Allow-Origin to an explicit list of trusted origins instead of `*`.',
    references: [],
  },
  'cookie-missing-secure': {
    title: 'Cookie set without the Secure flag',
    category: 'Cookies',
    severity: 'medium',
    description: 'A cookie is set without the `Secure` attribute.',
    attack: 'The cookie can be sent over an accidental plain-HTTP request (e.g. a stray http:// link, or a downgrade attack), where a network attacker can read it and hijack the session.',
    fix: 'Add the `Secure` attribute to every cookie so browsers only ever send it over HTTPS.',
    references: [],
  },
  'cookie-missing-httponly': {
    title: 'Cookie set without the HttpOnly flag',
    category: 'Cookies',
    severity: 'medium',
    description: 'A cookie is set without the `HttpOnly` attribute, which looks like a session/auth cookie.',
    attack: 'Client-side JavaScript can read this cookie. If the site has any XSS vulnerability anywhere (even a minor one), an attacker\'s injected script can steal this cookie directly and hijack the victim\'s session.',
    fix: 'Add the `HttpOnly` attribute to session and authentication cookies so they are inaccessible to JavaScript.',
    references: [],
  },
  'cookie-missing-samesite': {
    title: 'Cookie set without SameSite',
    category: 'Cookies',
    severity: 'low',
    description: 'A cookie is set without a `SameSite` attribute (or with `SameSite=None`).',
    attack: 'Without SameSite=Lax/Strict, the browser will attach this cookie to requests triggered from other sites — the classic setup for cross-site request forgery (CSRF), where an attacker\'s page silently submits actions (change email, transfer funds) using the victim\'s session.',
    fix: 'Set `SameSite=Lax` (or `Strict` for the most sensitive cookies). Only use `SameSite=None` when the cookie must be sent cross-site, and pair it with `Secure` and proper CSRF tokens.',
    references: ['OWASP: Cross-Site Request Forgery Prevention Cheat Sheet'],
  },
  'server-banner-disclosure': {
    title: 'Server software/version disclosed in headers',
    category: 'Information Disclosure',
    severity: 'info',
    description: 'The Server and/or X-Powered-By header reveals specific software and version numbers.',
    attack: 'Knowing the exact server software and version lets an attacker go straight to publicly known CVEs for that version instead of having to fingerprint it first — it speeds up reconnaissance, it doesn\'t create the vulnerability itself.',
    fix: 'Configure the web server / framework to omit or generalize the Server and X-Powered-By headers.',
    references: [],
  },
  'sensitive-file-exposed': {
    title: 'Sensitive file publicly accessible',
    category: 'Exposed Files',
    severity: 'critical',
    description: 'A file that should never be public (source control metadata, environment/config file, credentials, or a backup archive) is reachable at a predictable URL.',
    attack: 'An attacker who finds this URL (these paths are the first thing automated scanners try) can download it directly — no authentication needed. `.env`/config files often contain database passwords and API keys; `.git` exposure lets an attacker reconstruct the entire source history; backup archives can contain a full database dump.',
    fix: 'Remove the file from the web root (or block access to it at the web-server level), rotate any credentials it may have contained, and add these path patterns to the deploy process\'s exclude list so they never ship again.',
    references: ['OWASP: Top 10 - A05 Security Misconfiguration'],
  },
  'directory-listing-enabled': {
    title: 'Directory listing enabled',
    category: 'Information Disclosure',
    severity: 'medium',
    description: 'The web server returned a browsable directory index instead of a normal page.',
    attack: 'An attacker can browse the full file listing of that directory, discovering files that were never meant to be linked publicly (old backups, test scripts, internal notes).',
    fix: 'Disable directory autoindexing in the web server config (e.g. `Options -Indexes` in Apache, no autoindex in nginx).',
    references: [],
  },
  'mixed-content': {
    title: 'Mixed content: HTTPS page loads HTTP resources',
    category: 'Content Security',
    severity: 'medium',
    description: 'This HTTPS page loads one or more scripts, stylesheets, or other resources over plain HTTP.',
    attack: 'The HTTP resource is fetched without encryption, so a network attacker can tamper with it in transit — for an HTTP-loaded script, that means the attacker can inject arbitrary JavaScript into an otherwise-HTTPS page.',
    fix: 'Change every resource URL to https:// (or protocol-relative/relative URLs), and add a CSP `upgrade-insecure-requests` directive as a safety net.',
    references: [],
  },
  'outdated-js-library': {
    title: 'Outdated JavaScript library with known vulnerabilities',
    category: 'Content Security',
    severity: 'medium',
    description: 'The page loads a version of a front-end library that has publicly disclosed vulnerabilities.',
    attack: 'Because the vulnerable version and its CVEs are public knowledge, an attacker doesn\'t need to find a new bug — they can go straight to a known, documented exploit technique for that exact library version (commonly XSS or prototype-pollution style issues).',
    fix: 'Upgrade the library to a current, patched release.',
    references: [],
  },
  'security-txt-missing': {
    title: 'No security.txt file',
    category: 'Best Practice',
    severity: 'info',
    description: 'The site does not publish a /.well-known/security.txt file.',
    attack: 'Not an exploitable weakness — but without a published contact, a researcher who finds a real vulnerability has no clear, fast way to report it responsibly, which increases the odds it either goes unreported or gets disclosed publicly with no warning.',
    fix: 'Publish a `/.well-known/security.txt` file with a security contact, per RFC 9116.',
    references: ['securitytxt.org'],
  },
  'dangerous-http-methods': {
    title: 'Potentially dangerous HTTP methods enabled',
    category: 'HTTP Headers',
    severity: 'low',
    description: 'The server advertises support for state-changing or diagnostic HTTP methods (PUT, DELETE, TRACE, CONNECT) on this path.',
    attack: 'If these methods are actually wired up without proper authorization checks, PUT/DELETE could let an attacker write or remove content directly; TRACE can, on some old server/browser combinations, be used to read headers (including cookies) that JavaScript normally can\'t access (Cross-Site Tracing).',
    fix: 'Disable HTTP methods the application doesn\'t explicitly need at the web-server or framework routing level, and confirm any that remain enforce authentication and authorization.',
    references: [],
  },
  'robots-sensitive-hint': {
    title: 'robots.txt hints at sensitive paths',
    category: 'Information Disclosure',
    severity: 'info',
    description: 'robots.txt disallows crawling of paths whose names suggest admin panels, internal tools, or staging areas.',
    attack: 'robots.txt is a request to well-behaved crawlers, not an access control — it\'s public and often the very first thing an attacker reads, effectively handing them a map of paths the site owner considered sensitive enough to hide from search engines.',
    fix: 'Don\'t rely on robots.txt to hide anything sensitive; ensure these paths have real authentication, and only list them in robots.txt if that\'s acceptable to disclose.',
    references: [],
  },
};

const SEVERITY_ORDER = ['critical', 'high', 'medium', 'low', 'info'];
const SEVERITY_WEIGHT = { critical: 14, high: 8, medium: 4, low: 2, info: 0 };

module.exports = { KB, SEVERITY_ORDER, SEVERITY_WEIGHT };
